name: Run the tests

on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/biorbd_eigen
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/biorbd_eigen
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\biorbd_eigen
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: biorbd_eigen
          environment-file: environment_eigen.yml
        
      - name: Print mamba info
        run: | 
          mamba config --show
          mamba info
          mamba list
          
      - name: Install extra common dependencies
        run: | 
          mamba install cmake git pkgconfig swig pytest pytest-cov black -cconda-forge
          mamba list
          git submodule update --init --recursive

      - name: Install Linux dependencies
        run: |
          mamba install codecov lcov -cconda-forge
          mamba list
        if: matrix.label == 'linux-64'

      - name: Install Windows dependencies
        run: |
          mamba install ninja -cconda-forge
          mamba list
        if: matrix.label == 'win-64'

      - name: Setup environment variable
        run: |
          BIORBD_FOLDER=`pwd`
          BIORBD_BUILD_FOLDER=$BIORBD_FOLDER/build
          BIORBD_BUILD_COVERAGE_FOLDER=$BIORBD_FOLDER/build_coverage
          CONDA_ENV_PATH=$CONDA/envs/biorbd_eigen

      - name: Build biorbd UNIX
        run: |
          cd $BIORBD_FOLDER
          mkdir -p $BIORBD_BUILD_FOLDER
          cd $BIORBD_BUILD_FOLDER
          cmake -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DMATH_LIBRARY_BACKEND="Eigen3" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DMODULE_ACTUATORS=ON -DMODULE_KALMAN=ON -DMODULE_MUSCLES=ON -DBUILD_EXAMPLE=ON -DBINDER_C=ON -DBINDER_PYTHON3=ON ..
          make install
          cd $BIORBD_FOLDER
        if: matrix.label != 'win-64'
  
      - name: Build biorbd WINDOWS
        run: |
          cd $BIORBD_FOLDER
          mkdir -p $BIORBD_BUILD_FOLDER
          cd $BIORBD_BUILD_FOLDER
          cmake -GNinja -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH -DMATH_LIBRARY_BACKEND="Eigen3" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DMODULE_ACTUATORS=ON -DMODULE_KALMAN=ON -DMODULE_MUSCLES=ON -DBUILD_EXAMPLE=ON -DBINDER_C=ON -DBINDER_PYTHON3=ON ..
          cmake --build . --config Release --target install
          cd $BIORBD_FOLDER
        if: matrix.label == 'win-64'
